<a href="https://colab.research.google.com/github/amitranjan74/Performance_Automation/blob/main/Extract_Table_Using_OCR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project on extracting table Using OCR

In [ ]:
# Install system packages for OCR
!sudo apt-get update
!sudo apt-get install -y poppler-utils tesseract-ocr

# Install Python libraries for OCR
!pip install pdf2image pytesseract

import pytesseract
from pdf2image import convert_from_path
from PIL import Image
import os

# Although deepseek API doesn't directly offer PDF table extraction, we can leverage LLMs (e.g. `google.colab.ai`) after extracting text using OCR.
from google.colab import ai
import io

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (2,895 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
poppler-utils is already the newest version (22.02.0-2ubuntu0.12).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pytesseract in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from pdf2image) (11.3.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (26.0)

In [ ]:
# Define the path to your PDF file
pdf_path = "/content/Statement_CM.pdf"

# Check if the PDF file exists
if not os.path.exists(pdf_path):
    raise FileNotFoundError(f"The PDF file was not found at: {pdf_path}")

# Convert PDF to a list of images
print(f"Converting PDF '{pdf_path}' to images...")
images = convert_from_path(pdf_path)
print(f"Converted {len(images)} pages.")

ocr_text = ""
# Loop through each image and apply OCR
print("Extracting text from images using OCR...")
for i, image in enumerate(images):
    page_text = pytesseract.image_to_string(image)
    ocr_text += page_text + "\n" # Add newline between pages
    print(f"  - Page {i+1} OCR complete.")

print("\nOCR Extracted Text:")
print(ocr_text[:1000]) # Print first 1000 characters for brevity

Converting PDF '/content/Statement_CM.pdf' to images...
Converted 8 pages.
Extracting text from images using OCR...
  - Page 1 OCR complete.
  - Page 2 OCR complete.
  - Page 3 OCR complete.
  - Page 4 OCR complete.
  - Page 5 OCR complete.
  - Page 6 OCR complete.
  - Page 7 OCR complete.
  - Page 8 OCR complete.

OCR Extracted Text:
(A Depository Participant of NSDL)DP ID IN301549

Holding Statement as on : 17/03/2026 Business Date: 18/03/2026

DP Account No : 14726073
THIAGARAJAN ARAVAMUDAN

SUBAGHA

NO 131 (NEW 55) GANAPATHY NAGAR
T V KOIL POST

TRICHY

620005

Account Type : Free Balance

Sr. No. ISIN Company Name Scrip Balance Market Market Value
Type Rate

EQ
31 INFOTECH
INE748C01038 LIMITED FV RS. 65,500.000 13.150 8,61,325.000
10/-

| 2 1INE470A01017 |3M INDIA LIMITED 110.000] 33,148.100] 36,46,291.000

EQ
ABB INDIA
INE117A01022 LIMITED 800.000} 6,398.800] 51,19,040.000
ADITYA BIRLA
INE674K01013 CAPITAL LIMITED 900.000 324.750 2,92,275.000

ADITYA BIRLA
5 | INE647001011 | FASHION AND EQ 2,000.000 59.040 1,18,080.000
RETAIL LIMITED
ADITYA BIRLA
INE14LE01019 | LIFESTYLE EQ 2,000.000 97.800 1,95,600.000
BRANDS LIMITED

EQ
ADITYA BIRLA SUN | NEW
7] INE404A01024 LIFE AMC LIMITED | FV 700.000 977.200 6,84,040.000
Rs.5/-
ATHER ENERGY EQ FV
Zz INEOLEZ01016 LIMITED RE 1/- 100.000 761.850 76,185.000
BAJAJ AUTO
| 9 IN

Now that we have the text extracted using OCR, we'll pass it to `google.colab.ai` (accessing the Deepseek model) to identify and extract any tabular data into a JSON format.

In [ ]:
prompt_ocr = f"""
From the following text, extract any tabular data and present it in a structured JSON format.
If there are multiple tables, list them as separate objects in a JSON array.
If no table is found, return an empty JSON object.

Text:
{ocr_text}
"""

try:
    response_ocr = ai.generate_text(prompt=prompt_ocr)
    print("\nLLM Response (Extracted Table from OCR text):")
    print(response_ocr)
except Exception as e:
    print(f"\nAn error occurred while calling the AI model with OCR text: {e}")
    print("Please ensure you have access to the google.colab.ai service and your prompt is well-formed.")

print("\n---")

LLM Response (Extracted Table from OCR text):
```json
[
  {
    "Account Type": "Free Balance",
    "data": [
      {
        "Sr. No.": null,
        "ISIN": "INE748C01038",
        "Company Name": "31 INFOTECH LIMITED",
        "Scrip Type": "EQ FV RS. 10/-",
        "Balance": 65500.0,
        "Market Rate": 13.15,
        "Market Value": 861325.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 2,
        "ISIN": "INE470A01017",
        "Company Name": "3M INDIA LIMITED",
        "Scrip Type": null,
        "Balance": 110.0,
        "Market Rate": 33148.1,
        "Market Value": 3646291.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE117A01022",
        "Company Name": "ABB INDIA LIMITED",
        "Scrip Type": "EQ",
        "Balance": 800.0,
        "Market Rate": 6398.8,
        "Market Value": 5119040.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE674K01013",
        "Company Name": "ADITYA BIRLA CAPITAL LIMITED",
        "Scrip Type": null,
        "Balance": 900.0,
        "Market Rate": 324.75,
        "Market Value": 292275.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 5,
        "ISIN": "INE647001011",
        "Company Name": "ADITYA BIRLA FASHION AND RETAIL LIMITED",
        "Scrip Type": "EQ",
        "Balance": 2000.0,
        "Market Rate": 59.04,
        "Market Value": 118080.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE14LE01019",
        "Company Name": "ADITYA BIRLA LIFESTYLE BRANDS LIMITED",
        "Scrip Type": "EQ",
        "Balance": 2000.0,
        "Market Rate": 97.8,
        "Market Value": 195600.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 7,
        "ISIN": "INE404A01024",
        "Company Name": "ADITYA BIRLA SUN LIFE AMC LIMITED",
        "Scrip Type": "EQ NEW FV Rs.5/-",
        "Balance": 700.0,
        "Market Rate": 977.2,
        "Market Value": 684040.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE0LEZ01016",
        "Company Name": "ATHER ENERGY LIMITED",
        "Scrip Type": "EQ FV RE. 1/-",
        "Balance": 100.0,
        "Market Rate": 761.85,
        "Market Value": 76185.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 9,
        "ISIN": "INE917101010",
        "Company Name": "BAJAJ AUTO LIMITED",
        "Scrip Type": null,
        "Balance": 250.0,
        "Market Rate": 9206.5,
        "Market Value": 2301625.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE296A01024",
        "Company Name": "BAJAJ FINSERV LIMITED",
        "Scrip Type": null,
        "Balance": 9600.0,
        "Market Rate": 1779.35,
        "Market Value": 17081760.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 11,
        "ISIN": "INE118A01012",
        "Company Name": "BAJAJ HOLDINGS & INVESTMENT LIMITED.",
        "Scrip Type": "EQ",
        "Balance": 2150.0,
        "Market Rate": 9886.7,
        "Market Value": 21256405.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE213A01019",
        "Company Name": "BASF INDIA LIMITED",
        "Scrip Type": null,
        "Balance": 300.0,
        "Market Rate": 3461.0,
        "Market Value": 1038300.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 13,
        "ISIN": "INE462A01022",
        "Company Name": "BAYER CROPSCIENCE LIMITED",
        "Scrip Type": "EQ FV RS. 10/-",
        "Balance": 500.0,
        "Market Rate": 4483.45,
        "Market Value": 2241725.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 14,
        "ISIN": "INE263A01024",
        "Company Name": "BHARAT ELECTRONICS LIMITED",
        "Scrip Type": "EQ",
        "Balance": 12500.0,
        "Market Rate": 445.25,
        "Market Value": 5565625.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE257A01026",
        "Company Name": "BHARAT HEAVY ELECTRICALS LIMITED",
        "Scrip Type": null,
        "Balance": 11500.0,
        "Market Rate": 259.0,
        "Market Value": 2978500.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE397D01024",
        "Company Name": "BHARTI AIRTEL LIMITED",
        "Scrip Type": null,
        "Balance": 2750.0,
        "Market Rate": 1862.05,
        "Market Value": 5120637.5,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "IN9397D01014",
        "Company Name": "BHARTI AIRTEL LIMITED",
        "Scrip Type": null,
        "Balance": 250.0,
        "Market Rate": 1586.0,
        "Market Value": 396500.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE372E01025",
        "Company Name": "BIRLA PRECISION TECHNOLOGIES LIMITED",
        "Scrip Type": null,
        "Balance": 160000.0,
        "Market Rate": 30.6,
        "Market Value": 4896000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE836A01035",
        "Company Name": "BIRLASOFT LIMITED",
        "Scrip Type": null,
        "Balance": 10000.0,
        "Market Rate": 369.8,
        "Market Value": 3698000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE233B01017",
        "Company Name": "BLUE DART EXPRESS LIMITED",
        "Scrip Type": "EQ",
        "Balance": 150.0,
        "Market Rate": 5216.5,
        "Market Value": 782475.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 21,
        "ISIN": "INE323A01026",
        "Company Name": "BOSCH LIMITED",
        "Scrip Type": "EQ V.",
        "Balance": 25.0,
        "Market Rate": 31046.4,
        "Market Value": 776160.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE944T01017",
        "Company Name": "COFORGE LIMITED",
        "Scrip Type": "EQ",
        "Balance": 7500.0,
        "Market Rate": 1136.0,
        "Market Value": 8520000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 23,
        "ISIN": "INE259A01022",
        "Company Name": "COLGATE-PALMOLIVE (INDIA) LIMITED",
        "Scrip Type": null,
        "Balance": 400.0,
        "Market Rate": 1943.05,
        "Market Value": 777220.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE298A01020",
        "Company Name": "CUMMINS INDIA LIMITED",
        "Scrip Type": "EQ FV",
        "Balance": 700.0,
        "Market Rate": 4643.8,
        "Market Value": 3250660.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 25,
        "ISIN": "INE016A01026",
        "Company Name": "DABUR INDIA LIMITED",
        "Scrip Type": "EQ FV RE.1",
        "Balance": 2000.0,
        "Market Rate": 455.1,
        "Market Value": 910200.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE503A01015",
        "Company Name": "DCB BANK LIMITED",
        "Scrip Type": null,
        "Balance": 5000.0,
        "Market Rate": 172.95,
        "Market Value": 864750.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE271C01023",
        "Company Name": "DLF LIMITED",
        "Scrip Type": null,
        "Balance": 14850.0,
        "Market Rate": 556.3,
        "Market Value": 8261055.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 28,
        "ISIN": "INE532F01054",
        "Company Name": "EDELWEISS FINANCIAL SERVICES LIMITED",
        "Scrip Type": null,
        "Balance": 51000.0,
        "Market Rate": 111.45,
        "Market Value": 5683950.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 29,
        "ISIN": "INE129A01019",
        "Company Name": "GAIL (INDIA) LIMITED",
        "Scrip Type": null,
        "Balance": 4000.0,
        "Market Rate": 148.45,
        "Market Value": 593800.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 30,
        "ISIN": "INE776C01039",
        "Company Name": "GMR AIRPORTS LIMITED",
        "Scrip Type": "NEW FV Re.",
        "Balance": 900.0,
        "Market Rate": 91.25,
        "Market Value": 3102500.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 31,
        "ISIN": "INE0CU601026",
        "Company Name": "GMR POWER AND URBAN INFRA LIMITED",
        "Scrip Type": null,
        "Balance": 4000.0,
        "Market Rate": 105.2,
        "Market Value": 420800.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 32,
        "ISIN": "INE03JT01014",
        "Company Name": "GO DIGIT GENERAL INSURANCE LIMITED",
        "Scrip Type": null,
        "Balance": 100.0,
        "Market Rate": 329.9,
        "Market Value": 32990.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 33,
        "ISIN": "INE047A01021",
        "Company Name": "GRASIM INDUSTRIES LTD",
        "Scrip Type": null,
        "Balance": 450.0,
        "Market Rate": 2715.8,
        "Market Value": 1222110.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 34,
        "ISIN": "INE860A01027",
        "Company Name": "HCL TECHNOLOGIES LIMITED",
        "Scrip Type": "V.",
        "Balance": 4700.0,
        "Market Rate": 1373.1,
        "Market Value": 6453570.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE756101012",
        "Company Name": "HDB FINANCIAL SERVICES LIMITED",
        "Scrip Type": null,
        "Balance": 100.0,
        "Market Rate": 650.45,
        "Market Value": 65045.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 36,
        "ISIN": "INE040A01034",
        "Company Name": "HDFC BANK LIMITED",
        "Scrip Type": null,
        "Balance": 13300.0,
        "Market Rate": 838.8,
        "Market Value": 11156040.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 37,
        "ISIN": "INE038A01020",
        "Company Name": "HINDALCO INDUSTRIES LIMITED",
        "Scrip Type": null,
        "Balance": 13200.0,
        "Market Rate": 926.75,
        "Market Value": 12233100.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 38,
        "ISIN": "INE030A01027",
        "Company Name": "HINDUSTAN UNILEVER LIMITED",
        "Scrip Type": "V.",
        "Balance": 1550.0,
        "Market Rate": 2161.55,
        "Market Value": 3350402.5,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE267A01025",
        "Company Name": "HINDUSTAN ZINC LIMITED",
        "Scrip Type": "Vy.",
        "Balance": 10500.0,
        "Market Rate": 535.1,
        "Market Value": 5618550.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE07Y701011",
        "Company Name": "HITACHI ENERGY INDIA LIMITED",
        "Scrip Type": null,
        "Balance": 160.0,
        "Market Rate": 25230.0,
        "Market Value": 4036800.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 41,
        "ISIN": "INE191I01012",
        "Company Name": "HOUSING DEVELOPMENT AND INFRASTRUCTURE LIMITED",
        "Scrip Type": "EQ",
        "Balance": 51425.0,
        "Market Rate": 2.13,
        "Market Value": 109535.25,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE596H01014",
        "Company Name": "HOV SERVICES LIMITED",
        "Scrip Type": null,
        "Balance": 60000.0,
        "Market Rate": 48.0,
        "Market Value": 2880000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE703H01016",
        "Company Name": "HUBTOWN LIMITED",
        "Scrip Type": null,
        "Balance": 12000.0,
        "Market Rate": 197.1,
        "Market Value": 2365200.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 44,
        "ISIN": "INE275B01026",
        "Company Name": "HUHTAMAKI INDIA LIMITED",
        "Scrip Type": "EQ NEW RS. 2/-",
        "Balance": 12000.0,
        "Market Rate": 166.95,
        "Market Value": 2003400.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 45,
        "ISIN": "INE346A01027",
        "Company Name": "ICICI PRUDENTIAL ASSET MGMT. CO.LTD",
        "Scrip Type": "EQ NEW FV",
        "Balance": 6.0,
        "Market Rate": 2955.0,
        "Market Value": 17730.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE565A01014",
        "Company Name": "IDBI OVERSEAS",
        "Scrip Type": null,
        "Balance": 42000.0,
        "Market Rate": 32.42,
        "Market Value": 1361640.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 47,
        "ISIN": "INE665F01015",
        "Company Name": "INFO EDGE (INDIA) LIMITED",
        "Scrip Type": null,
        "Balance": 3500.0,
        "Market Rate": 1003.2,
        "Market Value": 3511200.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 49,
        "ISIN": "INE875A01025",
        "Company Name": "IVRCL LIMITED",
        "Scrip Type": "EQ",
        "Balance": 330000.0,
        "Market Rate": 0.4,
        "Market Value": 132000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 50,
        "ISIN": "INE175A01022",
        "Company Name": "JAIN IRRIGATION SYSTEMS LIMITED",
        "Scrip Type": "E-V",
        "Balance": 22000.0,
        "Market Rate": 30.8,
        "Market Value": 677600.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE758E01017",
        "Company Name": "JIO FINANCIAL SERVICES LIMITED",
        "Scrip Type": null,
        "Balance": 1900.0,
        "Market Rate": 244.5,
        "Market Value": 464550.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 52,
        "ISIN": "INE643A01035",
        "Company Name": "JTEKT INDIA LIMITED",
        "Scrip Type": "EQ NEW RE. 1/-",
        "Balance": 14851.0,
        "Market Rate": 128.65,
        "Market Value": 1910581.15,
        "Status": "Free"
      },
      {
        "Sr. No.": 53,
        "ISIN": "INE587G01015",
        "Company Name": "KAYA LIMITED",
        "Scrip Type": null,
        "Balance": 28.0,
        "Market Rate": 297.0,
        "Market Value": 8316.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 54,
        "ISIN": "INE972A01020",
        "Company Name": "KOTHARI INDUSTRIAL CORPORATION LIMITED",
        "Scrip Type": null,
        "Balance": 210.0,
        "Market Rate": 178.0,
        "Market Value": 37380.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 55,
        "ISIN": "INE041401011",
        "Company Name": "KPIT TECHNOLOGIES LIMITED",
        "Scrip Type": "EQ",
        "Balance": 9765.0,
        "Market Rate": 689.0,
        "Market Value": 6728085.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE2KCE01013",
        "Company Name": "KWALITY WALL'S (INDIA) LIMITED",
        "Scrip Type": null,
        "Balance": 1550.0,
        "Market Rate": 24.58,
        "Market Value": 38099.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 57,
        "ISIN": "INE785C01048",
        "Company Name": "LANCO INFRATECH LIMITED",
        "Scrip Type": "EQ NEW RE. 1/-",
        "Balance": 335000.0,
        "Market Rate": 1.0,
        "Market Value": 335000.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 58,
        "ISIN": "INE115A01026",
        "Company Name": "LIC HOUSING FINANCE LTD",
        "Scrip Type": "V.",
        "Balance": 8385.0,
        "Market Rate": 504.35,
        "Market Value": 4228974.75,
        "Status": "Free"
      },
      {
        "Sr. No.": 59,
        "ISIN": "INE0J1Y01017",
        "Company Name": "LIFE INSURANCE CORPORATION OF INDIA",
        "Scrip Type": null,
        "Balance": 200.0,
        "Market Rate": 785.6,
        "Market Value": 157120.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE153A01019",
        "Company Name": "MAHANAGAR TELEPHONE NIGAM LIMITED",
        "Scrip Type": null,
        "Balance": 167000.0,
        "Market Rate": 25.5,
        "Market Value": 4258500.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 61,
        "ISIN": "INE196A01016",
        "Company Name": "MARICO LIMITED",
        "Scrip Type": null,
        "Balance": 3000.0,
        "Market Rate": 753.7,
        "Market Value": 2261100.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 62,
        "ISIN": "INE490G01020",
        "Company Name": "MOIL LIMITED",
        "Scrip Type": "EQ",
        "Balance": 6000.0,
        "Market Rate": 295.55,
        "Market Value": 1773300.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 63,
        "ISIN": "INE139A01034",
        "Company Name": "NATIONAL ALUMINIUM COMPANY LIMITED",
        "Scrip Type": "V.",
        "Balance": 19700.0,
        "Market Rate": 385.65,
        "Market Value": 7597305.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 64,
        "ISIN": "INE848E01016",
        "Company Name": "NHPC LIMITED",
        "Scrip Type": null,
        "Balance": 76000.0,
        "Market Rate": 77.01,
        "Market Value": 5852760.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INF204KB1412",
        "Company Name": "NIPPON INDIA MUTUAL FUND",
        "Scrip Type": null,
        "Balance": 4000.0,
        "Market Rate": 269.19,
        "Market Value": 1076760.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE846H01039",
        "Company Name": "NISSAN COPPER LIMITED",
        "Scrip Type": null,
        "Balance": 525000.0,
        "Market Rate": 0.75,
        "Market Value": 393750.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 67,
        "ISIN": "INE531F01023",
        "Company Name": "NUVAMA WEALTH MANAGEMENT LIMITED",
        "Scrip Type": null,
        "Balance": 2875.0,
        "Market Rate": 1173.0,
        "Market Value": 3372375.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 68,
        "ISIN": "INE274J01014",
        "Company Name": "OIL INDIA LIMITED",
        "Scrip Type": null,
        "Balance": 6525000.0,
        "Market Rate": 469.95,
        "Market Value": 3066423.75,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE191A01027",
        "Company Name": "ORCHID PHARMA LIMITED",
        "Scrip Type": "EQ",
        "Balance": 580.0,
        "Market Rate": 533.95,
        "Market Value": 309691.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 70,
        "ISIN": "INE182A01018",
        "Company Name": "PFIZER LIMITED",
        "Scrip Type": null,
        "Balance": 285.0,
        "Market Rate": 4814.0,
        "Market Value": 1371990.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE202B01038",
        "Company Name": "PIRAMAL FINANCE LIMITED",
        "Scrip Type": "EQ NEW FVRS 2/-",
        "Balance": 4300.0,
        "Market Rate": 1778.5,
        "Market Value": 7647550.0,
        "Status": "Free"
      },
      {
        "Sr. No.": null,
        "ISIN": "INE0DKS501011",
        "Company Name": "PIRAMAL PHARMA LIMITED",
        "Scrip Type": null,
        "Balance": 20100.0,
        "Market Rate": 143.95,
        "Market Value": 2893395.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 73,
        "ISIN": "INE752E01010",
        "Company Name": "POWER GRID CORPORATION OF INDIA LIMITED",
        "Scrip Type": "EQ",
        "Balance": 3900.0,
        "Market Rate": 302.8,
        "Market Value": 1180920.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 74,
        "ISIN": "INE614A01028",
        "Company Name": "PRAKASH INDUSTRIES",
        "Scrip Type": "EQ",
        "Balance": 8250.0,
        "Market Rate": 267.7,
        "Market Value": 2208525.0,
        "Status": "Free"
      },
      {
        "Sr. No.": 75,

In [ ]:
import pandas as pd
import json

# Assuming response_ocr contains the JSON string from the previous step
# It's good practice to ensure it's a string before parsing
json_data_str = response_ocr

# Some LLMs might wrap JSON in markdown code blocks, so we'll try to extract it.
if json_data_str.strip().startswith('```json') and json_data_str.strip().endswith('```'):
    json_data_str = json_data_str.strip()[len('```json'):-len('```')]

In [ ]:
data = json.loads(json_data_str)

In [ ]:
data

[{'Account Type': 'Free Balance',
  'data': [{'Sr. No.': None,
    'ISIN': 'INE748C01038',
    'Company Name': '31 INFOTECH LIMITED',
    'Scrip Type': 'EQ FV RS. 10/-',
    'Balance': 65500.0,
    'Market Rate': 13.15,
    'Market Value': 861325.0,
    'Status': 'Free'},
   {'Sr. No.': 2,
    'ISIN': 'INE470A01017',
    'Company Name': '3M INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 110.0,
    'Market Rate': 33148.1,
    'Market Value': 3646291.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE117A01022',
    'Company Name': 'ABB INDIA LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 800.0,
    'Market Rate': 6398.8,
    'Market Value': 5119040.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE674K01013',
    'Company Name': 'ADITYA BIRLA CAPITAL LIMITED',
    'Scrip Type': None,
    'Balance': 900.0,
    'Market Rate': 324.75,
    'Market Value': 292275.0,
    'Status': 'Free'},
   {'Sr. No.': 5,
    'ISIN': 'INE647001011',
    'Company Name': 'ADITYA BIRLA FASHION AND RETAIL LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 2000.0,
    'Market Rate': 59.04,
    'Market Value': 118080.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE14LE01019',
    'Company Name': 'ADITYA BIRLA LIFESTYLE BRANDS LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 2000.0,
    'Market Rate': 97.8,
    'Market Value': 195600.0,
    'Status': 'Free'},
   {'Sr. No.': 7,
    'ISIN': 'INE404A01024',
    'Company Name': 'ADITYA BIRLA SUN LIFE AMC LIMITED',
    'Scrip Type': 'EQ NEW FV Rs.5/-',
    'Balance': 700.0,
    'Market Rate': 977.2,
    'Market Value': 684040.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE0LEZ01016',
    'Company Name': 'ATHER ENERGY LIMITED',
    'Scrip Type': 'EQ FV RE. 1/-',
    'Balance': 100.0,
    'Market Rate': 761.85,
    'Market Value': 76185.0,
    'Status': 'Free'},
   {'Sr. No.': 9,
    'ISIN': 'INE917101010',
    'Company Name': 'BAJAJ AUTO LIMITED',
    'Scrip Type': None,
    'Balance': 250.0,
    'Market Rate': 9206.5,
    'Market Value': 2301625.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE296A01024',
    'Company Name': 'BAJAJ FINSERV LIMITED',
    'Scrip Type': None,
    'Balance': 9600.0,
    'Market Rate': 1779.35,
    'Market Value': 17081760.0,
    'Status': 'Free'},
   {'Sr. No.': 11,
    'ISIN': 'INE118A01012',
    'Company Name': 'BAJAJ HOLDINGS & INVESTMENT LIMITED.',
    'Scrip Type': 'EQ',
    'Balance': 2150.0,
    'Market Rate': 9886.7,
    'Market Value': 21256405.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE213A01019',
    'Company Name': 'BASF INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 300.0,
    'Market Rate': 3461.0,
    'Market Value': 1038300.0,
    'Status': 'Free'},
   {'Sr. No.': 13,
    'ISIN': 'INE462A01022',
    'Company Name': 'BAYER CROPSCIENCE LIMITED',
    'Scrip Type': 'EQ FV RS. 10/-',
    'Balance': 500.0,
    'Market Rate': 4483.45,
    'Market Value': 2241725.0,
    'Status': 'Free'},
   {'Sr. No.': 14,
    'ISIN': 'INE263A01024',
    'Company Name': 'BHARAT ELECTRONICS LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 12500.0,
    'Market Rate': 445.25,
    'Market Value': 5565625.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE257A01026',
    'Company Name': 'BHARAT HEAVY ELECTRICALS LIMITED',
    'Scrip Type': None,
    'Balance': 11500.0,
    'Market Rate': 259.0,
    'Market Value': 2978500.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE397D01024',
    'Company Name': 'BHARTI AIRTEL LIMITED',
    'Scrip Type': None,
    'Balance': 2750.0,
    'Market Rate': 1862.05,
    'Market Value': 5120637.5,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'IN9397D01014',
    'Company Name': 'BHARTI AIRTEL LIMITED',
    'Scrip Type': None,
    'Balance': 250.0,
    'Market Rate': 1586.0,
    'Market Value': 396500.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE372E01025',
    'Company Name': 'BIRLA PRECISION TECHNOLOGIES LIMITED',
    'Scrip Type': None,
    'Balance': 160000.0,
    'Market Rate': 30.6,
    'Market Value': 4896000.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE836A01035',
    'Company Name': 'BIRLASOFT LIMITED',
    'Scrip Type': None,
    'Balance': 10000.0,
    'Market Rate': 369.8,
    'Market Value': 3698000.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE233B01017',
    'Company Name': 'BLUE DART EXPRESS LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 150.0,
    'Market Rate': 5216.5,
    'Market Value': 782475.0,
    'Status': 'Free'},
   {'Sr. No.': 21,
    'ISIN': 'INE323A01026',
    'Company Name': 'BOSCH LIMITED',
    'Scrip Type': 'EQ V.',
    'Balance': 25.0,
    'Market Rate': 31046.4,
    'Market Value': 776160.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE944T01017',
    'Company Name': 'COFORGE LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 7500.0,
    'Market Rate': 1136.0,
    'Market Value': 8520000.0,
    'Status': 'Free'},
   {'Sr. No.': 23,
    'ISIN': 'INE259A01022',
    'Company Name': 'COLGATE-PALMOLIVE (INDIA) LIMITED',
    'Scrip Type': None,
    'Balance': 400.0,
    'Market Rate': 1943.05,
    'Market Value': 777220.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE298A01020',
    'Company Name': 'CUMMINS INDIA LIMITED',
    'Scrip Type': 'EQ FV',
    'Balance': 700.0,
    'Market Rate': 4643.8,
    'Market Value': 3250660.0,
    'Status': 'Free'},
   {'Sr. No.': 25,
    'ISIN': 'INE016A01026',
    'Company Name': 'DABUR INDIA LIMITED',
    'Scrip Type': 'EQ FV RE.1',
    'Balance': 2000.0,
    'Market Rate': 455.1,
    'Market Value': 910200.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE503A01015',
    'Company Name': 'DCB BANK LIMITED',
    'Scrip Type': None,
    'Balance': 5000.0,
    'Market Rate': 172.95,
    'Market Value': 864750.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE271C01023',
    'Company Name': 'DLF LIMITED',
    'Scrip Type': None,
    'Balance': 14850.0,
    'Market Rate': 556.3,
    'Market Value': 8261055.0,
    'Status': 'Free'},
   {'Sr. No.': 28,
    'ISIN': 'INE532F01054',
    'Company Name': 'EDELWEISS FINANCIAL SERVICES LIMITED',
    'Scrip Type': None,
    'Balance': 51000.0,
    'Market Rate': 111.45,
    'Market Value': 5683950.0,
    'Status': 'Free'},
   {'Sr. No.': 29,
    'ISIN': 'INE129A01019',
    'Company Name': 'GAIL (INDIA) LIMITED',
    'Scrip Type': None,
    'Balance': 4000.0,
    'Market Rate': 148.45,
    'Market Value': 593800.0,
    'Status': 'Free'},
   {'Sr. No.': 30,
    'ISIN': 'INE776C01039',
    'Company Name': 'GMR AIRPORTS LIMITED',
    'Scrip Type': 'NEW FV Re.',
    'Balance': 900.0,
    'Market Rate': 91.25,
    'Market Value': 3102500.0,
    'Status': 'Free'},
   {'Sr. No.': 31,
    'ISIN': 'INE0CU601026',
    'Company Name': 'GMR POWER AND URBAN INFRA LIMITED',
    'Scrip Type': None,
    'Balance': 4000.0,
    'Market Rate': 105.2,
    'Market Value': 420800.0,
    'Status': 'Free'},
   {'Sr. No.': 32,
    'ISIN': 'INE03JT01014',
    'Company Name': 'GO DIGIT GENERAL INSURANCE LIMITED',
    'Scrip Type': None,
    'Balance': 100.0,
    'Market Rate': 329.9,
    'Market Value': 32990.0,
    'Status': 'Free'},
   {'Sr. No.': 33,
    'ISIN': 'INE047A01021',
    'Company Name': 'GRASIM INDUSTRIES LTD',
    'Scrip Type': None,
    'Balance': 450.0,
    'Market Rate': 2715.8,
    'Market Value': 1222110.0,
    'Status': 'Free'},
   {'Sr. No.': 34,
    'ISIN': 'INE860A01027',
    'Company Name': 'HCL TECHNOLOGIES LIMITED',
    'Scrip Type': 'V.',
    'Balance': 4700.0,
    'Market Rate': 1373.1,
    'Market Value': 6453570.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE756101012',
    'Company Name': 'HDB FINANCIAL SERVICES LIMITED',
    'Scrip Type': None,
    'Balance': 100.0,
    'Market Rate': 650.45,
    'Market Value': 65045.0,
    'Status': 'Free'},
   {'Sr. No.': 36,
    'ISIN': 'INE040A01034',
    'Company Name': 'HDFC BANK LIMITED',
    'Scrip Type': None,
    'Balance': 13300.0,
    'Market Rate': 838.8,
    'Market Value': 11156040.0,
    'Status': 'Free'},
   {'Sr. No.': 37,
    'ISIN': 'INE038A01020',
    'Company Name': 'HINDALCO INDUSTRIES LIMITED',
    'Scrip Type': None,
    'Balance': 13200.0,
    'Market Rate': 926.75,
    'Market Value': 12233100.0,
    'Status': 'Free'},
   {'Sr. No.': 38,
    'ISIN': 'INE030A01027',
    'Company Name': 'HINDUSTAN UNILEVER LIMITED',
    'Scrip Type': 'V.',
    'Balance': 1550.0,
    'Market Rate': 2161.55,
    'Market Value': 3350402.5,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE267A01025',
    'Company Name': 'HINDUSTAN ZINC LIMITED',
    'Scrip Type': 'Vy.',
    'Balance': 10500.0,
    'Market Rate': 535.1,
    'Market Value': 5618550.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE07Y701011',
    'Company Name': 'HITACHI ENERGY INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 160.0,
    'Market Rate': 25230.0,
    'Market Value': 4036800.0,
    'Status': 'Free'},
   {'Sr. No.': 41,
    'ISIN': 'INE191I01012',
    'Company Name': 'HOUSING DEVELOPMENT AND INFRASTRUCTURE LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 51425.0,
    'Market Rate': 2.13,
    'Market Value': 109535.25,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE596H01014',
    'Company Name': 'HOV SERVICES LIMITED',
    'Scrip Type': None,
    'Balance': 60000.0,
    'Market Rate': 48.0,
    'Market Value': 2880000.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE703H01016',
    'Company Name': 'HUBTOWN LIMITED',
    'Scrip Type': None,
    'Balance': 12000.0,
    'Market Rate': 197.1,
    'Market Value': 2365200.0,
    'Status': 'Free'},
   {'Sr. No.': 44,
    'ISIN': 'INE275B01026',
    'Company Name': 'HUHTAMAKI INDIA LIMITED',
    'Scrip Type': 'EQ NEW RS. 2/-',
    'Balance': 12000.0,
    'Market Rate': 166.95,
    'Market Value': 2003400.0,
    'Status': 'Free'},
   {'Sr. No.': 45,
    'ISIN': 'INE346A01027',
    'Company Name': 'ICICI PRUDENTIAL ASSET MGMT. CO.LTD',
    'Scrip Type': 'EQ NEW FV',
    'Balance': 6.0,
    'Market Rate': 2955.0,
    'Market Value': 17730.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE565A01014',
    'Company Name': 'IDBI OVERSEAS',
    'Scrip Type': None,
    'Balance': 42000.0,
    'Market Rate': 32.42,
    'Market Value': 1361640.0,
    'Status': 'Free'},
   {'Sr. No.': 47,
    'ISIN': 'INE665F01015',
    'Company Name': 'INFO EDGE (INDIA) LIMITED',
    'Scrip Type': None,
    'Balance': 3500.0,
    'Market Rate': 1003.2,
    'Market Value': 3511200.0,
    'Status': 'Free'},
   {'Sr. No.': 49,
    'ISIN': 'INE875A01025',
    'Company Name': 'IVRCL LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 330000.0,
    'Market Rate': 0.4,
    'Market Value': 132000.0,
    'Status': 'Free'},
   {'Sr. No.': 50,
    'ISIN': 'INE175A01022',
    'Company Name': 'JAIN IRRIGATION SYSTEMS LIMITED',
    'Scrip Type': 'E-V',
    'Balance': 22000.0,
    'Market Rate': 30.8,
    'Market Value': 677600.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE758E01017',
    'Company Name': 'JIO FINANCIAL SERVICES LIMITED',
    'Scrip Type': None,
    'Balance': 1900.0,
    'Market Rate': 244.5,
    'Market Value': 464550.0,
    'Status': 'Free'},
   {'Sr. No.': 52,
    'ISIN': 'INE643A01035',
    'Company Name': 'JTEKT INDIA LIMITED',
    'Scrip Type': 'EQ NEW RE. 1/-',
    'Balance': 14851.0,
    'Market Rate': 128.65,
    'Market Value': 1910581.15,
    'Status': 'Free'},
   {'Sr. No.': 53,
    'ISIN': 'INE587G01015',
    'Company Name': 'KAYA LIMITED',
    'Scrip Type': None,
    'Balance': 28.0,
    'Market Rate': 297.0,
    'Market Value': 8316.0,
    'Status': 'Free'},
   {'Sr. No.': 54,
    'ISIN': 'INE972A01020',
    'Company Name': 'KOTHARI INDUSTRIAL CORPORATION LIMITED',
    'Scrip Type': None,
    'Balance': 210.0,
    'Market Rate': 178.0,
    'Market Value': 37380.0,
    'Status': 'Free'},
   {'Sr. No.': 55,
    'ISIN': 'INE041401011',
    'Company Name': 'KPIT TECHNOLOGIES LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 9765.0,
    'Market Rate': 689.0,
    'Market Value': 6728085.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE2KCE01013',
    'Company Name': "KWALITY WALL'S (INDIA) LIMITED",
    'Scrip Type': None,
    'Balance': 1550.0,
    'Market Rate': 24.58,
    'Market Value': 38099.0,
    'Status': 'Free'},
   {'Sr. No.': 57,
    'ISIN': 'INE785C01048',
    'Company Name': 'LANCO INFRATECH LIMITED',
    'Scrip Type': 'EQ NEW RE. 1/-',
    'Balance': 335000.0,
    'Market Rate': 1.0,
    'Market Value': 335000.0,
    'Status': 'Free'},
   {'Sr. No.': 58,
    'ISIN': 'INE115A01026',
    'Company Name': 'LIC HOUSING FINANCE LTD',
    'Scrip Type': 'V.',
    'Balance': 8385.0,
    'Market Rate': 504.35,
    'Market Value': 4228974.75,
    'Status': 'Free'},
   {'Sr. No.': 59,
    'ISIN': 'INE0J1Y01017',
    'Company Name': 'LIFE INSURANCE CORPORATION OF INDIA',
    'Scrip Type': None,
    'Balance': 200.0,
    'Market Rate': 785.6,
    'Market Value': 157120.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE153A01019',
    'Company Name': 'MAHANAGAR TELEPHONE NIGAM LIMITED',
    'Scrip Type': None,
    'Balance': 167000.0,
    'Market Rate': 25.5,
    'Market Value': 4258500.0,
    'Status': 'Free'},
   {'Sr. No.': 61,
    'ISIN': 'INE196A01016',
    'Company Name': 'MARICO LIMITED',
    'Scrip Type': None,
    'Balance': 3000.0,
    'Market Rate': 753.7,
    'Market Value': 2261100.0,
    'Status': 'Free'},
   {'Sr. No.': 62,
    'ISIN': 'INE490G01020',
    'Company Name': 'MOIL LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 6000.0,
    'Market Rate': 295.55,
    'Market Value': 1773300.0,
    'Status': 'Free'},
   {'Sr. No.': 63,
    'ISIN': 'INE139A01034',
    'Company Name': 'NATIONAL ALUMINIUM COMPANY LIMITED',
    'Scrip Type': 'V.',
    'Balance': 19700.0,
    'Market Rate': 385.65,
    'Market Value': 7597305.0,
    'Status': 'Free'},
   {'Sr. No.': 64,
    'ISIN': 'INE848E01016',
    'Company Name': 'NHPC LIMITED',
    'Scrip Type': None,
    'Balance': 76000.0,
    'Market Rate': 77.01,
    'Market Value': 5852760.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INF204KB1412',
    'Company Name': 'NIPPON INDIA MUTUAL FUND',
    'Scrip Type': None,
    'Balance': 4000.0,
    'Market Rate': 269.19,
    'Market Value': 1076760.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE846H01039',
    'Company Name': 'NISSAN COPPER LIMITED',
    'Scrip Type': None,
    'Balance': 525000.0,
    'Market Rate': 0.75,
    'Market Value': 393750.0,
    'Status': 'Free'},
   {'Sr. No.': 67,
    'ISIN': 'INE531F01023',
    'Company Name': 'NUVAMA WEALTH MANAGEMENT LIMITED',
    'Scrip Type': None,
    'Balance': 2875.0,
    'Market Rate': 1173.0,
    'Market Value': 3372375.0,
    'Status': 'Free'},
   {'Sr. No.': 68,
    'ISIN': 'INE274J01014',
    'Company Name': 'OIL INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 6525000.0,
    'Market Rate': 469.95,
    'Market Value': 3066423.75,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE191A01027',
    'Company Name': 'ORCHID PHARMA LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 580.0,
    'Market Rate': 533.95,
    'Market Value': 309691.0,
    'Status': 'Free'},
   {'Sr. No.': 70,
    'ISIN': 'INE182A01018',
    'Company Name': 'PFIZER LIMITED',
    'Scrip Type': None,
    'Balance': 285.0,
    'Market Rate': 4814.0,
    'Market Value': 1371990.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE202B01038',
    'Company Name': 'PIRAMAL FINANCE LIMITED',
    'Scrip Type': 'EQ NEW FVRS 2/-',
    'Balance': 4300.0,
    'Market Rate': 1778.5,
    'Market Value': 7647550.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE0DKS501011',
    'Company Name': 'PIRAMAL PHARMA LIMITED',
    'Scrip Type': None,
    'Balance': 20100.0,
    'Market Rate': 143.95,
    'Market Value': 2893395.0,
    'Status': 'Free'},
   {'Sr. No.': 73,
    'ISIN': 'INE752E01010',
    'Company Name': 'POWER GRID CORPORATION OF INDIA LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 3900.0,
    'Market Rate': 302.8,
    'Market Value': 1180920.0,
    'Status': 'Free'},
   {'Sr. No.': 74,
    'ISIN': 'INE614A01028',
    'Company Name': 'PRAKASH INDUSTRIES',
    'Scrip Type': 'EQ',
    'Balance': 8250.0,
    'Market Rate': 267.7,
    'Market Value': 2208525.0,
    'Status': 'Free'},
   {'Sr. No.': 75,
    'ISIN': 'INE002A01018',
    'Company Name': 'RELIANCE INDUSTRIES LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 3690.0,
    'Market Rate': 1408.8,
    'Market Value': 5198472.0,
    'Status': 'Free'},
   {'Sr. No.': 76,
    'ISIN': 'INE614G01033',
    'Company Name': 'RELIANCE POWER LIMITED',
    'Scrip Type': None,
    'Balance': 33200.0,
    'Market Rate': 22.55,
    'Market Value': 748660.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE293A01013',
    'Company Name': 'ROLTA INDIA LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 13500.0,
    'Market Rate': 1.62,
    'Market Value': 21870.0,
    'Status': 'Free'},
   {'Sr. No.': 78,
    'ISIN': 'INE639K01016',
    'Company Name': 'SATCHMO HOLDINGS LIMITED',
    'Scrip Type': 'E',
    'Balance': 228500.0,
    'Market Rate': 3.38,
    'Market Value': 772330.0,
    'Status': 'Free'},
   {'Sr. No.': 79,
    'ISIN': 'INE0PB301013',
    'Company Name': 'SHIPPING CORPORATION OF INDIA LAND AND ASSETS LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 44000.0,
    'Market Rate': 41.95,
    'Market Value': 1845800.0,
    'Status': 'Free'},
   {'Sr. No.': 80,
    'ISIN': 'INE721A01047',
    'Company Name': 'SHRIRAM FINANCE LIMITED',
    'Scrip Type': 'EQ NEW RE.2/-',
    'Balance': 1875.0,
    'Market Rate': 1013.75,
    'Market Value': 1900781.25,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE1NPPO1017',
    'Company Name': 'SIEMENS ENERGY INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 700.0,
    'Market Rate': 2875.9,
    'Market Value': 2013130.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE003A01024',
    'Company Name': 'SIEMENS LIMITED',
    'Scrip Type': None,
    'Balance': 700.0,
    'Market Rate': 3218.0,
    'Market Value': 2252600.0,
    'Status': 'Free'},
   {'Sr. No.': 83,
    'ISIN': 'INE671H01015',
    'Company Name': 'SOBHA LIMITED',
    'Scrip Type': None,
    'Balance': 2300.0,
    'Market Rate': 1294.95,
    'Market Value': 2978385.0,
    'Status': 'Free'},
   {'Sr. No.': 84,
    'ISIN': 'INE114A01011',
    'Company Name': 'STEEL AUTHORITY OF INDIA LIMITED',
    'Scrip Type': None,
    'Balance': 15500.0,
    'Market Rate': 155.85,
    'Market Value': 2415675.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE272O01018',
    'Company Name': 'SUN PAPER MILL LIMITED',
    'Scrip Type': None,
    'Balance': 1300.0,
    'Market Rate': 10.0,
    'Market Value': 13000.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE044A01036',
    'Company Name': 'SUN INDUSTRIES LIMITED',
    'Scrip Type': None,
    'Balance': 5300.0,
    'Market Rate': 1802.75,
    'Market Value': 9554575.0,
    'Status': 'Free'},
   {'Sr. No.': 87,
    'ISIN': 'INE483C01032',
    'Company Name': 'TANLA PLATFORMS LIMITED',
    'Scrip Type': 'EQ',
    'Balance': 400000.0,
    'Market Rate': 434.0,
    'Market Value': 173600000.0,
    'Status': 'Free'},
   {'Sr. No.': 88,
    'ISIN': 'INE976I01016',
    'Company Name': 'TATA CAPITAL LIMITED',
    'Scrip Type': None,
    'Balance': 400.0,
    'Market Rate': 315.65,
    'Market Value': 126260.0,
    'Status': 'Free'},
   {'Sr. No.': None,
    'ISIN': 'INE467B01029',
    'Company Name': 'TATA CONSULTANCY SERVICES LIMITED',
    'Scrip Type': None,
    'Balance': 200.0,
    'Market Rate': 165000.0,
    'Market Value': None,
    'Status': 'Free'},
   {'Sr. No.': 90,
    'ISIN': 'INE192A01025',
    'Company Name': 'TATA CONSUMER PRODUCTS LIMITED',
    'Scrip Type': None,
    'Balance': 900.0,

In [ ]:


try:

    # Initialize an empty list to store DataFrames
    dataframes = []

    # Iterate through the list of tables (each table is an object in the list)
    for table_obj in data:
        # Check if 'data' key exists and is a list of dictionaries
        if 'data' in table_obj and isinstance(table_obj['data'], list):
            df = pd.DataFrame(table_obj['data'])
            # Add a title if available
            if 'title' in table_obj:
                df.name = table_obj['title']
            elif 'Account Type' in table_obj:
                df.name = f"Table for Account Type: {table_obj['Account Type']}"
            dataframes.append(df)
        else:
            print(f"Skipping object as 'data' key is missing or not a list: {table_obj}")

    # Display each created DataFrame
    if dataframes:
        for i, df in enumerate(dataframes):
            print(f"\n--- Table {i+1}: {getattr(df, 'name', 'Untitled Table')} ---")
            df.to_csv(f"table_{i+1}.csv", index=False)
            display(df.head())
    else:
        print("No dataframes could be created from the JSON.")

except json.JSONDecodeError as e:
    print(f"Error decoding JSON: {e}")
    print("Please ensure the LLM response is valid JSON.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

--- Table 1: Table for Account Type: Free Balance ---

,Sr. No.,ISIN,Company Name,Scrip Type,Balance,Market Rate,Market Value,Status
0,NaN,INE748C01038,31 INFOTECH LIMITED,EQ FV RS. 10/-,65500.0,13.15,861325.0,Free
1,2.0,INE470A01017,3M INDIA LIMITED,None,110.0,33148.10,3646291.0,Free
2,NaN,INE117A01022,ABB INDIA LIMITED,EQ,800.0,6398.80,5119040.0,Free
3,NaN,INE674K01013,ADITYA BIRLA CAPITAL LIMITED,None,900.0,324.75,292275.0,Free
4,5.0,INE647001011,ADITYA BIRLA FASHION AND RETAIL LIMITED,EQ,2000.0,59.04,118080.0,Free

--- Table 2: Table for Account Type: Pledge a/c ---

,Sr. No.,ISIN,Company Name,Scrip Type,Balance,Market Rate,Market Value,Status
0,NaN,INE029A01011,BHARAT PETROLEUM CORPORATION LIMITED,EQ,15000.0,303.30,4549500.0,None
1,2.0,INE081A01020,TATA STEEL LIMITED,EQ NEW 5.7 pp 1).,33300.0,195.05,6495165.0,None